application: devquest2015
version: v2
runtime: go
api_version: go1


handlers:

- url: /api/.*
  script: _go_app

- url: /
  static_files: index.html
  upload: index.html

- url: /
  static_files: scores.html
  upload: scores.html

- url: /(.*\.(css|gif|png|jpg|ico|js|html|ttf|json|svg|woff|eot|xcf))
  static_files: \1
  upload: (.*\.(css|gif|png|jpg|ico|js|html|ttf|json|svg|woff|eot|xcf))



skip_files:
- ^node_modules/*.*
- ^\.git/*.*
#- ^\assets/*.*
#- ^\lib/*.*
#- ^\src/*.*
#- ^(.*/)?.*\.go$

includes:
- app_env.yaml
