application: devquest2015
version: v1
runtime: go
api_version: go1


handlers:

- url: /api/.*
  script: _go_app

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(css|gif|png|jpg|ico|js|html))
  static_files: \1
  upload: (.*\.(css|gif|png|jpg|ico|js|html))



skip_files:
- ^node_modules/*.*
- ^\.git/*.*
#- ^\assets/*.*
#- ^\lib/*.*
#- ^\src/*.*
#- ^(.*/)?.*\.go$



