application: devquest2015
version: v1
runtime: go
api_version: go1


handlers:
#- url: /
#  static_files: index.html
#  upload: index.html
# access the static resources in the root director
#- url: /(.*)
#  static_files: \1
#  upload: (.*)
#- url: /api/.*
- url: /.*
  script: _go_app
skip_files:
- ^node_modules/*.*
- ^\.git/*.*
- ^\assets/*.*
- ^\lib/*.*
- ^\src/*.*
#- ^(.*/)?.*\.go$



