application: devquest2015
version: 1
runtime: go
api_version: go1


handlers:
- url: /.*
  script: _go_app
#handlers:
#- url: /
#  static_files: index.html
#  upload: index.html

# access the static resources in the root director

#- url: /(.*)
#  static_files: \1
#  upload: (.*)
