'use strict';


module.exports = {
	GOOGLE_CLIENT : '<GOOGLE_CLIENT>',
	TWITTER_CLIENT : '<TWITTER_CLIENT>',
	TWITTER_CLIENT_SECRET : '<TWITTER_CLIENT_SECRET>',
	GITHUB_CLIENT : '<GITHUB_CLIENT>',
	GITHUB_CLIENT_SECRET : '<GITHUB_CLIENT_SECRET>'
}